---
title: "Zones UNESCO"
subtitle: "Fiche indicateur n°100"
---
Superficie des intersections avec les zones inscrites au patrimoine mondial de l'UNESCO

## Identification

 | Libelle | Valeur |
|:---|:---|
| **Identifiant de l’indicateur** | 100 |
| **Famille** | Enjeux Environnementaux |
| **Type d’indicateur** | Enjeu |
| **Unité** | ha |
| **Support spatial** | maille |
| **Pondération** | Non |
| **Spatialisation H3** | Non |

## Objectif
Identifier les zones à haute valeur patrimoniale mondiale susceptibles d'être impactées par les pressions sur la ressource en eau.

## Méthode de normalisation
Classes 3 niveaux

## Sens de l’indicateur
Positif (absence = critique / plus = mieux)

## Définition de la criticité
Présence d’une partie du bassin versant dans zone UNESCO = criticité faible bien que  enjeu fort


## Modalité de visualition 

| Libelle |  Valeur | 
|:---|:---|
| **Nature des données** | Quantitatif |
| **Discret ou continu** | Continue |
| **Relatif ou absolu** | Absolu |
| **Représentation cartographique** | Carte choroplèthe |

##  Sources de données

### zones inscrites au patrimoine mondial de l'UNESCO
- Origine : CEN
- Distributeur : GEOREP
- Couverture spatiale: Nouvelle-calédonie
- Actualisation : jamais

[Accéder à la ressource](https://georep-dtsi-sgt.opendata.arcgis.com/maps/e17f6c38b47a435e9e73c102a7a1b933/about)

