---
title: "Zones protégées provinciales"
subtitle: "Fiche indicateur n°101"
---
Superficie des intersections avec parcs, réserves

## Identification

 | Libelle | Valeur |
|:---|:---|
| **Identifiant de l’indicateur** | 101 |
| **Famille** | Enjeux Environnementaux |
| **Type d’indicateur** | Enjeu |
| **Unité** | ha |
| **Support spatial** | maille |
| **Pondération** | Non |
| **Spatialisation H3** | Non |

## Objectif
Caractériser le niveau de protection réglementaire du milieu naturel autour des ressources en eau.

## Méthode de normalisation
Classes 3 niveaux

## Sens de l’indicateur
Positif (absence = critique / plus = mieux)

## Définition de la criticité
Présence en zone protégée = criticité faible bien que  enjeu fort


## Modalité de visualition 

| Libelle |  Valeur | 
|:---|:---|
| **Nature des données** | Quantitatif |
| **Discret ou continu** | Continue |
| **Relatif ou absolu** | Absolu |
| **Représentation cartographique** | Carte choroplèthe |

##  Sources de données

### Aires protégées de la Province Sud
- Origine : PSUD
- Distributeur : PSUD
- Couverture spatiale: Province Sud
- Actualisation : inconnu


### Aires protégées de la Province Nord
- Origine : PNORD
- Distributeur : PNORD
- Couverture spatiale: Province Nord
- Actualisation : inconnu


### Aires protégées de la Province des Iles
- Origine : PIL
- Distributeur : PIL
- Couverture spatiale: Province des Iles
- Actualisation : inconnu

