---
title: "Espèces menacées (Forêt sèche)"
subtitle: "Fiche indicateur n°104"
---
Superficie des intersections des patchs de forêt sèche

## Identification

 | Libelle | Valeur |
|:---|:---|
| **Identifiant de l’indicateur** | 104 |
| **Famille** | Enjeux Environnementaux |
| **Type d’indicateur** | Enjeu |
| **Unité** | ha |
| **Support spatial** | maille |
| **Pondération** | Non |
| **Spatialisation H3** | Non |

## Objectif
Identifier la présence de forêt sèche, écosystème endémique parmi les plus menacés de Nouvelle-Calédonie.

## Méthode de normalisation
Classes 3 niveaux

## Sens de l’indicateur
Négatif (absence = critique) ?

## Définition de la criticité
Présence de forêt sèche  = criticité faible bien que enjeu fort (à confirmer)


## Modalité de visualition 

| Libelle |  Valeur | 
|:---|:---|
| **Nature des données** | Quantitatif |
| **Discret ou continu** | Continue |
| **Relatif ou absolu** | Absolu |
| **Représentation cartographique** | Carte choroplèthe |

##  Sources de données

### Forêt sèche – Indices de vulnérabilité
- Origine : CEN
- Distributeur : GEOREP
- Couverture spatiale: Nouvelle-calédonie
- Actualisation : inconnu

[Accéder à la ressource](https://georep-dtsi-sgt.opendata.arcgis.com/maps/b9304b72009f45e6aa4fc2fab702e98b)

