---
title: "Longueur réseau"
subtitle: "Fiche indicateur n°2"
---
Longueur totale des canalisations d’eau potable.

## Identification

 | Libelle | Valeur |
|:---|:---|
| **Identifiant de l’indicateur** | 2 |
| **Famille** | Enjeux AEP |
| **Type d’indicateur** | Enjeu |
| **Unité** | km |
| **Support spatial** | UD |
| **Pondération** | Oui |
| **Spatialisation H3** | Non |

## Objectif
Comparer l’importance des infrastructures dépendantes de chaque captage afin d’identifier ceux dont la défaillance aurait le plus d’impact.

## Méthode de normalisation
Classes 3 niveaux

## Sens de l’indicateur
Positif (absence = critique / plus = mieux)

## Définition de la criticité
Plus le réseau est long, plus les enjeux sont élevés → criticité stratégique élevée

## Synthèse échanges Stéphane du 24 avril 2026
Donnée UD (unité de distribution). Problème de structuration base DAS (non relationnelle). Attention aux doublons si plusieurs captages alimentent une même UD.


## Modalité de visualition 

| Libelle |  Valeur | 
|:---|:---|
| **Nature des données** | Quantitatif |
| **Discret ou continu** | Continue |
| **Relatif ou absolu** | Absolu |
| **Représentation cartographique** | Cercle proportionnel |

##  Sources de données

### unité de distribution (nom à vérifier)
- Origine : DASS
- Actualisation : inconnu

