---
title: "Activité minière"
subtitle: "Fiche indicateur n°301"
---
Surface occupée par les activités minières.

## Identification

 | Libelle | Valeur |
|:---|:---|
| **Identifiant de l’indicateur** | 301 |
| **Famille** | Pressions Anthropiques |
| **Type d’indicateur** | Pression |
| **Unité** | ha |
| **Support spatial** | maille |
| **Pondération** | Oui |
| **Spatialisation H3** | Oui |

## Objectif
Comparer les bassins versants selon l’emprise minière afin d’identifier les pressions fortes sur la ressource.

## Méthode de normalisation
Classes 3 niveaux

## Sens de l’indicateur
Négatif (plus = critique)

## Définition de la criticité
Surface minière élevée = pression forte → criticité élevée

## Synthèse échanges Stéphane du 24 avril 2026
Donnée DIMENC non publique. Alternative via MOS (redondance sol nu). Accès incertain.


## Modalité de visualition 

| Libelle |  Valeur | 
|:---|:---|
| **Nature des données** | Quantitatif |
| **Discret ou continu** | Continue |
| **Relatif ou absolu** | Absolu |
| **Représentation cartographique** | Carte choroplèthe |

##  Sources de données

### CARTOGRAPHIE – OCCUPATION DES SOLS (MOS 2014 – classes végétation)
- Origine : OEIL/GOUV
- Distributeur : GEOREP
- Couverture spatiale: Nouvelle-calédonie
- Actualisation : jamais

[Accéder à la ressource](https://georep-dtsi-sgt.opendata.arcgis.com/documents/b1efecab06904c9996127a3ff5bdc586/about)


### Exploitation minière en Nouvelle-Calédonie : centres miniers et usines métallurgiques
- Origine : DIMENC
- Distributeur : GEOREP
- Couverture spatiale: Nouvelle-calédonie
- Actualisation : inconnu

[Accéder à la ressource](https://dtsi-sgt.maps.arcgis.com/home/item.html?id=4e485fd6879142d9b52fe1bcea0c2cb1)


### cadastre minier actif (concessions, permis de recherches et réserves techniques provinciales) et échu
- Origine : DIMENC
- Distributeur : GEOREP
- Couverture spatiale: Nouvelle-calédonie
- Actualisation : inconnu

[Accéder à la ressource](https://dtsi-sgt.maps.arcgis.com/home/item.html?id=e70295d0f4994702ad2d64e6c4156377)

