---
title: "Urbanisation (nombre de bâtis)"
subtitle: "Fiche indicateur n°303"
---
Nombre de bâtis

## Identification

 | Libelle | Valeur |
|:---|:---|
| **Identifiant de l’indicateur** | 303 |
| **Famille** | Pressions Anthropiques |
| **Type d’indicateur** | Pression |
| **Unité** | Nombre |
| **Support spatial** | maille |
| **Pondération** | Oui |
| **Spatialisation H3** | Oui |

## Objectif
Quantifier la densité de bâti comme indicateur de pression anthropique directe sur la ressource.

## Méthode de normalisation
Classes 3 niveaux

## Sens de l’indicateur
Négatif (plus = critique)

## Définition de la criticité
Forte densité bâtie = pression élevée


## Modalité de visualition 

| Libelle |  Valeur | 
|:---|:---|
| **Nature des données** | Quantitatif |
| **Discret ou continu** | Discrète |
| **Relatif ou absolu** | Absolu |
| **Représentation cartographique** | Carte choroplèthe |

##  Sources de données

### BDTOPO-NC
- Origine : DITTT
- Distributeur : DITTT
- Couverture spatiale: Nouvelle-calédonie
- Actualisation : annuelle

