---
title: "AODPE nombre"
subtitle: "Fiche indicateur n°503"
---
Nombre de prélèvements d’eau autorisés.

## Identification

 | Libelle | Valeur |
|:---|:---|
| **Identifiant de l’indicateur** | 503 |
| **Famille** | Pressions Quantitatives |
| **Type d’indicateur** | Pression |
| **Unité** | Nombre |
| **Support spatial** | Captage |
| **Pondération** | Oui |
| **Spatialisation H3** | Non |

## Objectif
Comparer les captages selon le nombre de prélèvements afin d’évaluer la pression d’usage.

## Méthode de normalisation
Classes 3 niveaux

## Sens de l’indicateur
Négatif (plus = critique)

## Définition de la criticité
Plus de prélèvements = pression ressource

## Synthèse échanges Stéphane du 24 avril 2026
Indicateur pression captage. Donnée dynamique DAVAR. Intégrable en analyse.


## Modalité de visualition 

| Libelle |  Valeur | 
|:---|:---|
| **Nature des données** | Quantitatif |
| **Discret ou continu** | Discrète |
| **Relatif ou absolu** | Absolu |
| **Représentation cartographique** | Cercle proportionnel |

##  Sources de données

### AODPE
- Origine : DAVAR
- Distributeur : GEOREP
- Couverture spatiale: Nouvelle-calédonie
- Actualisation : inconnu

