project:
  type: book
  pre-render: generate_fiches_indicateurs.py
date: today
date-format: long
lang: fr
logo:
  light:
    path: ressources/OEIL_logo.png
  dark:
    path: ressources/OEIL_logo.png
image_font_1: ressources/MJunckerOEIL.jpg
image_font_2: ressources/eau-monitoring.png
logo_partenaire: ressources/logo_yapuka.png
book:
  title: Fiches indicateurs HydroScope
  subtitle: Catalogue des indicateurs de suivi et de comparaison des unités de gestion
    AEP
  author: Hugo Roussaffa
  chapters:
  - index.qmd
  - fiches/1.qmd
  - fiches/2.qmd
  - fiches/3.qmd
  - fiches/4.qmd
  - fiches/5.qmd
  - fiches/6.qmd
  - fiches/7.qmd
  - fiches/8.qmd
  - fiches/9.qmd
  - fiches/10.qmd
  - fiches/100.qmd
  - fiches/101.qmd
  - fiches/102.qmd
  - fiches/103.qmd
  - fiches/104.qmd
  - fiches/105.qmd
  - fiches/106.qmd
  - fiches/107.qmd
  - fiches/200.qmd
  - fiches/201.qmd
  - fiches/202.qmd
  - fiches/203.qmd
  - fiches/204.qmd
  - fiches/300.qmd
  - fiches/301.qmd
  - fiches/302.qmd
  - fiches/304.qmd
  - fiches/305.qmd
  - fiches/306.qmd
  - fiches/500.qmd
  - fiches/501.qmd
  - fiches/502.qmd
  - fiches/503.qmd
  - fiches/504.qmd
  - fiches/505.qmd
  - fiches/400.qmd
  - fiches/401.qmd
  - fiches/402.qmd
  downloads:
  - pdf
format:
  typst:
    margin-geometry:
      outer:
        far: 5mm
        width: 2in
        separation: 0.25in
      inner:
        far: 5mm
        width: 2in
        separation: 0.25in
      clearance: 8pt
    toc: true
    toc-depth: 1
    number-sections: false
    fontsize: 11pt
    lang: fr
  pdf-oeil:
    pdf-engine: xelatex
    header-includes:
    - \usepackage{soul}
    - \sethlcolor{yellow}
    toc: true
    colorlinks: true
    toc-depth: 1
    fig-width: 8
    fig-height: 6
    fig-pos: H
    number-sections: false
    keep_tex: false
    include-in-header:
    - in-header.tex
    - header.tex
    fontsize: 11pt
    mainfont: Calibri
    template-partials:
    - before-body.tex
  docx:
    reference-doc: custom-reference.docx
    toc: true
    toc-depth: 2
    number-sections: true
    highlight-style: github
  html:
    theme: cosmo
    toc: true
    lang: fr
